// Code generated by "stringer -type=LockType"; DO NOT EDIT.

package rebounds

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BASE-1]
}

const _LockType_name = "BASE"

var _LockType_index = [...]uint8{0, 4}

func (i LockType) String() string {
	i -= 1
	if i < 0 || i >= LockType(len(_LockType_index)-1) {
		return "LockType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _LockType_name[_LockType_index[i]:_LockType_index[i+1]]
}
